version: "3"
services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
     - 8000
     - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
