version: '3'
services:
  postgres:
    image: "postgres"
    container_name: postgres
    restart: always
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=password
  pgadmin4:
    image: "dpage/pgadmin4"
    restart: always
    environment: 
     - PGADMIN_DEFAULT_EMAIL=admin@foo.com
     - PGADMIN_DEFAULT_PASSWORD=password
    ports:
     - "8080:80"
    links:
     - "postgres:pgsql-server"